### ISSUE TITLE
Export metadata

### ISSUE THREAD

**Issue by albertotn** [mirkoperillo/resting#103]
## Expected Behavior
When user export a collection, metadata should be sincronized to resting version

## Actual Behavior
Right now if user export an empty collection, following export is provided:

```
{
	"log": {
		"version": "1.1",
		"creator": {
			"name": "Resting WebExtension",
			"version": "1.0"
		},
		"entries": [],
		"_contexts": [
			{
				"name": "default",
				"variables": []
			}
		]
	}
}
```

I'm not sure what are these versions, should be related to current resting version ?

## Steps to Reproduce the Problem

  1. start resting
  1. export metadata
  1. read metadata

## Specifications

  - Addon Version: 0.15.0
  - Firefox Version: 71.0
  - OS: Windows 10

**Comment by mirkoperillo** [comment]
Hi,
those metadata belongs to HAR standard and are not strongly bind to Resting version
I'll put some inline notes below to explain the meaning of the fields

```
{
	"log": {
		"version": "1.1",  <-- HAR standard version
		"creator": {
			"name": "Resting WebExtension", <-- name of the producer
			"version": "1.0" <--  export schema version
		},
		"entries": [],
		"_contexts": [
			{
				"name": "default",
				"variables": []
			}
		]
	}
}
```
Feel free to ask to have more details
