### ISSUE TITLE
More visible contextual menu

### ISSUE THREAD

**Issue by mirkoperillo** [mirkoperillo/resting#111]
Resting offers a contextual menu to access some bookmarks features clicking the right mouse button.
I understand that this feature is not clear / visible to most of the users.

The idea is to render this more accessible putting a button in place of the delete button (that will be moved into the menu)

![cxt_menu_screen](https://user-images.githubusercontent.com/4171821/81777759-cd437200-94f1-11ea-8ebc-dae79d51778f.png)

**Comment by alexmario74** [comment]
I would like to work on this.

**Comment by mirkoperillo** [comment]
Thank you @alexmario74 , I assign it to you
