### ISSUE TITLE
Progress indicator

### ISSUE THREAD

**Issue by albertotn** [mirkoperillo/resting#115]
## Expected Behavior

When you send a request to a remote server, sometimes takes more than 1 second, so an actual progress indicator that request is fired and we are waiting for an answer from remote server is needed.

## Actual Behavior

When you make a request, if this takes some times, you don't know what is going on

## Steps to Reproduce the Problem

  1. make a request to a slow serve
  1. wait for answer
  1. do it again

## Specifications

  - Addon Version: 1.0.3
  - Firefox Version: 80.0.1
  - OS: Windows 10

**Comment by mirkoperillo** [comment]
@albertotn you are absolutely right.
This is a necessary feature.

**Comment by albertotn** [comment]
Maybe also this feature could be labeled as helpwanted or good first issue ? For the next hacktoberfest 👍

**Comment by mirkoperillo** [comment]
Yes why not, you are right.
Let's try.

**Comment by luisgregson** [comment]
I'd like to work on this issue if possible. Can it be assigned to me please?

**Comment by mirkoperillo** [comment]
wonderful @luisgregson , thank you..it's yours !

**Comment by mirkoperillo** [comment]
@albertotn thank you to @luisgregson the next release of Resting  will have a visual progress indicator  for a request.
