### ISSUE TITLE
Bookmark enhancement

### ISSUE THREAD

**Issue by albertotn** [mirkoperillo/resting#116]
## Expected Behavior
Bookmark could be enhanced with some automatic information, like method name (GET/POST/ecc... )  using a color and a search box ( using method type as an optional filter )

## Actual Behavior
Right now a great number of bookmarks means a list with same background and color.
To make this list easy to use, I have to put method name inside bookmark name, but is a waste of time and there is no way to search in bookmarks

## Steps to Reproduce the Problem

  1. build a request
  1. save it as bookmark

## Specifications

  - Addon Version: 1.0.3
  - Firefox Version: 80.0.1
  - OS: Windows 10

**Comment by mirkoperillo** [comment]
@albertotn you are right, it could be useful.
At the moment the workaround is to leave the bookmark name empty, the default one is method name + request url

**Comment by albertotn** [comment]
I've see the fix on #117 by @KwanJunWen ( great work by the way, I want to try and test it on next release!), but I've notice a little "feature".
If you build a request like GET /hello and press save, by default bookmark name is saved.
But If you change your request, add a parameter, like GET /hello?name=Test, boomark will be overwritten.

This behaviour is strange for me, because I would have expected to see a new bookmark.

What do you think @mirkoperillo  ?

**Comment by mirkoperillo** [comment]
I think I miss something @albertotn.
If I edit a bookmark I expect that when I save it, the new values will override the existing ones.

To take an example if I open a text file using my editor and I edit the text, when I save it I expect that the editor overrides the content of the file with the edited one and not create a new file.
Your flow is like a "Save as" action for me (and btw this flow is supported by Resting too).

What am I missing ?

**Comment by albertotn** [comment]
You got the right point, but when you edit a text file, you modify the file's content, not the title.
In the case of resting, request and bookmark title are the same, so for me is a little bit confusing

**Comment by mirkoperillo** [comment]
I wanna understand better, so I propose you another scenario @albertotn 

1. I create a request GET /hello
2. I save it given the name "hello wolrd"
3. OMG a typo ! I edit the bookmark and change the name in "hello world!" and saving it

What result do you expect ?

**Comment by albertotn** [comment]
An update bookmark, but problem here is not this, is the lack of preview when you save the bookmark I think

**Comment by albertotn** [comment]
Also another bug related.

1) open a saved bookmark
2) change something
3) save it
4) in the bookmark window, clear bookmark name => Resting here overwrite existing bookmark, but default bookmark name should create a new bookmark, right ?

**Comment by mirkoperillo** [comment]
> Also another bug related.
> 
>     1. open a saved bookmark
> 
>     2. change something
> 
>     3. save it
> 
>     4. in the bookmark window, clear bookmark name => Resting here overwrite existing bookmark, but default bookmark name should create a new bookmark, right ?


Sorry I totally miss the point, can you expose a complete reproducible test case ( with explicit data)

Thank you a lot to help improving Resting

**Comment by albertotn** [comment]
Sure!

1) create a simple GET as follows:

![immagine](https://user-images.githubusercontent.com/12526457/94605379-52f56d80-0299-11eb-962d-21af182c8c0c.png)

2) save it with name test:

![immagine](https://user-images.githubusercontent.com/12526457/94605620-abc50600-0299-11eb-8a37-c764a38b1392.png)

3) on the bookmark you can see saved one:

![immagine](https://user-images.githubusercontent.com/12526457/94605642-b1225080-0299-11eb-91bc-78a2b9c61e44.png)

4) now load saved bookmark

5) click save, but don't do nothing for now:

![immagine](https://user-images.githubusercontent.com/12526457/94605696-c26b5d00-0299-11eb-852b-6bac32d450ca.png)

then clear saved bookmark name and click save:

![immagine](https://user-images.githubusercontent.com/12526457/94605751-d747f080-0299-11eb-822b-c1e3312ffe5f.png)

6) now in the bookmark the name is default one, but I've put no text in bookmark name:

![immagine](https://user-images.githubusercontent.com/12526457/94605839-efb80b00-0299-11eb-91e4-74d9c7ef8229.png)

I think for users this behaviour is confusing.

**Comment by mirkoperillo** [comment]
What do you think about fill the name field with the default placeholder when the bookmark name remains empty ?
So in your example when you remove the name, you have a visual feedback about what the name will contain.

Let me know

**Comment by albertotn** [comment]
For me is fine to clarify how it works
