### ISSUE TITLE
Disable save button when the URL field is empty

### ISSUE THREAD

**Issue by mirkoperillo** [mirkoperillo/resting#119]
## Expected Behavior

If the URL field is empty the save button should be disabled

## Actual Behavior

It is possible to save a request with empty URL

## Steps to Reproduce the Problem

  1. Open Resting
  1. Leave the URL field empty
  1. Click save button

## Specifications

  - Addon Version:  All
  - Firefox Version: All
  - OS: All

**Comment by vyasriday** [comment]
hey i can take this one.

**Comment by mirkoperillo** [comment]
Thank you !

Il sab 26 set 2020, 15:22 Hridayesh Sharma <notifications@github.com> ha
scritto:

**Comment by mirkoperillo** [comment]
go deep in the provided PR, there is a strange side-effect that kills the user experience: button is enabled or disabled only when the focus is removed from the url input field.
