### ISSUE TITLE
Show right placeholder when the input field is empty

### ISSUE THREAD

**Issue by mirkoperillo** [mirkoperillo/resting#121]
## Expected Behavior

When I remove the name of a bookmark I want to see a placeholder with method and url of the request.
Ref to #116 

## Actual Behavior

When I remove the name of a saved bookmark the showed placeholder is wrong: it should show the default value ( method + url) instead of the name of bookmark ( that I'm trying to remove).

## Steps to Reproduce the Problem

  1. Save a bookmark with a name
  2. Load the bookmark
  3. Open the save bookmark dialog
  3. Remove the bookmark name field

## Specifications

  - Addon Version: Master branch

**Comment by clockwerkz** [comment]
I'd like to work on this issue.

**Comment by mirkoperillo** [comment]
Hi @clockwerkz 
ok it's yours !

**Comment by clockwerkz** [comment]
Thanks!

**Comment by clockwerkz** [comment]
I dug into this last night, I should have a PR or at least a progress status by tonight. :)

**Comment by mirkoperillo** [comment]
Thank you @clockwerkz, today I'll try it
