### ISSUE TITLE
Improve bookmark list style

### ISSUE THREAD

**Issue by albertotn** [mirkoperillo/resting#122]
## Expected Behavior
As user I want to quickly understand, when I have many bookmarks, where these bookmarks are

## Actual Behavior
Right now all bookmarks inside a folder has same background color, so for me is not so easy to understand

## Steps to Reproduce the Problem

  1. create a bookmark folder
  1. save many bookmarks ( at least 20 )

## Specifications

  - Addon Version: 1.0.3
  - Firefox Version: 81.0
  - OS: Windows 10

## Proposed solution

My solution here is alternating a different color for bookmarks, between current white and a light gray, like [#ddd ](https://htmlcolors.com/hex/ddd).
If you want, I can try to pull a PR for this

**Comment by mirkoperillo** [comment]
@albertotn it's a good proposal. Thank you for offering to implement the solution.
I assign this issue to you

**Comment by mirkoperillo** [comment]
@albertotn are you still working on this or I can consider this issue unassigned ?

**Comment by albertotn** [comment]
Yes I'm on this, when will be ready I don't know
