### ISSUE TITLE
Share collections between users

### ISSUE THREAD

**Issue by albertotn** [mirkoperillo/resting#130]
## Expected Behavior

Users should be able to share with colleagues their collections.
One step to avoid vendor lock in could be to provide a pluggable mechanism and let community build different kind of share options, like share using google drive, dropbox, github, gist, etc...

Note: I know it's a vague request, so I can rephrase it like "As use I want to be able to share my collection of requests with my colleague in order to explain some rest calls"

## Actual Behavior

Right now is not possible

## Steps to Reproduce the Problem

  1. build a large collection of requests
  1. ?

## Specifications

  - Addon Version: 1.0.3
  - Firefox Version: 82.0.2
  - OS: Windows 10

**Comment by mirkoperillo** [comment]
@albertotn currently Resting permits a bulk export of all bookmarks ( and I know this solution doesn't fit your use case).

What do you think about a selective export ? ( Something like export the bookmarks inside a folder  or a selection of bookmarks )

**Comment by mirkoperillo** [comment]
@albertotn the last release of Resting (v1.10.0) includes the possibility to export a folder of bookmarks or a single bookmark (see #206 for details)

I think it's a simple solution to satisfy this request.

I close this issue

I close this issue
