### ISSUE TITLE
This App is getting annoying, ctrl + c not possible!

### ISSUE THREAD

**Issue by venomone** [mirkoperillo/resting#134]
Why the hell does your tool have this enforced copy action on every field I focus on and then press ctrl + c ?
I want to copy a value of an input field, not the whole response ...

This behavior is super annoying, please remove your involvement according to auto-copy stuff and ctrl+c or at least provide an option to disable it!

merci :)

**Comment by mirkoperillo** [comment]
Hi @venomone 

you are right, this is a bug.
I'm going to fix it asap

thank you for reporting it

**Comment by venomone** [comment]
> Hi @venomone
> 
> you are right, this is a bug. I'm going to fix it asap
> 
> thank you for reporting it

Thank you very much :D
Besides, it would be awesome if elements in the bookmark sections are sortable, either via ABC or dragging the element upwards or downwards the bookmark list, but this has nothing to do with this bug.

**Comment by mirkoperillo** [comment]
> Besides, it would be awesome if elements in the bookmark sections are sortable, either via ABC or dragging the element upwards or downwards the bookmark list, but this has nothing to do with this bug.

Absolutely right, this is a thing that annoying me too.
There is an already opened issue on that #18

**Comment by mirkoperillo** [comment]
@venomone fixed the problem.

Force the update of Firefox extensions to have the new fixed version.

issue fixed by efb79ee3e52908a2e8c8d21e1a127766a1684644
