### ISSUE TITLE
Feature request: Make Bookmark items draggable/sortable

### ISSUE THREAD

**Issue by venomone** [mirkoperillo/resting#136]
Hey,

I really like your plugin, I'm almost working daily with it, but I really miss the function that I can drag my bookmark items up and down.
I have a lot of endpoints, about 60 on my app, so it's kinda annoying to always look for the right bookmark as there is pure chaos in the Bookmark side menu.
Can you please add this small feature? Would be Awesome :dagger: 

Thanks in advance.

**Comment by mirkoperillo** [comment]
@venomone you are absolutely right, I'm going to work on it for the next release.

Ref to #18

**Comment by venomone** [comment]
Thank you so much, would love to see that feature :D

**Comment by mirkoperillo** [comment]
Hi @venomone Resting v1.3.0 has been published for Firefox and for Chrome (soon).
Now you have the possibility to sort alphabetically your folders and bookmarks (even the nested ones)

**Comment by venomone** [comment]
Thank you very much for your time and work, really appreciate that. 🍭
