### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by luvarqpp** [mirkoperillo/resting#138]
## Missing thing
I have started to use resting, but just before first POST request I was in need of some sample usage. Brief tutorial, or one minute video. I do not see anything like "on-boarding helper". I would like to know how to make use-case like "login to backend, get bearer jwt token (just any string) and pass it to other get request".

Is it reasonable to make some simple start-up wiki page? Perhaps animated gif would be enough to grasp idea behind contexts and so on.

## Specifications

  - Addon Version: 1.3.1
  - Firefox Version: 96.0 (64-bit)
  - OS: some ubuntu

**Comment by mirkoperillo** [comment]
@luvarqpp thank you for you feedback.
In this moment there isn't any sort of on-boarding process to use Resting.

I know that this is a limitation, in particular for some advanced, and currently not so clear, operations as contexts and variables usage.

You are perfectly right, some tutorial guides could be reasonable and useful.
A wiki or some tutorial section in the resting site could be a good solution.

This is a very time-expensive operation, so I think I will to deal with it in the next future.

**Comment by luvarqpp** [comment]
@mirkoperillo would it make sense to paste here some small markdown with tutorial "how to log in for bearer token and how to use it in call" and other one "how to bookmark some call"? I am willing to write something small, what I have figured out till now... Perhaps with screen-shoots if it would help.

**Comment by mirkoperillo** [comment]
First of all thank you to be interested in contribute to Resting @luvarqpp.
I can propose you this possibility: you can create a Pull Request with a file `TUTORIAL.md` to put in the root of the project.
This file can be organized with sections, every section describes a tutorial of a usage scenario.

What do you think about ?
