### ISSUE TITLE
Har import goes in error

### ISSUE THREAD

**Issue by albertotn** [mirkoperillo/resting#139]
## Expected Behavior
User should not be able to import har file with no file selection

## Actual Behavior
Right now and user can select to import:

![image](https://user-images.githubusercontent.com/12526457/153356386-84286a1e-79bf-47b3-9a5c-6e584a1c2bf7.png)

and with no selection:

![image](https://user-images.githubusercontent.com/12526457/153356468-7eb1e4f8-3c82-4ef9-8923-10cc3852750c.png)

if the user select to import and click there is an error on the console:
```

Uncaught TypeError: FileReader.readAsText: Argument 1 is not an object.
    _handleImport moz-extension://408b8366-32a2-43e5-b28e-a3c54d19c6f4/js/app/components/bookmarks/bookmarksVm.js:238
    importBookmarks moz-extension://408b8366-32a2-43e5-b28e-a3c54d19c6f4/js/app/components/bookmarks/bookmarksVm.js:158
    init moz-extension://408b8366-32a2-43e5-b28e-a3c54d19c6f4/js/vendor/knockout-3.4.2.js:90
    jQuery 2
```

but no feedback for the user

## Steps to Reproduce the Problem

  1. open resting
  1. select to import an har file
  1. click import  2. 

## Specifications

  - Addon Version: 1.3.1
  - Firefox Version: 97.0
  - OS: Windows 10

**Comment by mirkoperillo** [comment]
Absolutely right.
Thank for reporting this @albertotn
