### ISSUE TITLE
What is the eqivalent to curl -d or --data with Resting?

### ISSUE THREAD

**Issue by venomone** [mirkoperillo/resting#149]
Hey folks,

im currently trying to figure out how I can make this curl request working in resting:

curl --insecure \
  -X POST \
  -H "Content-Type: application/json" \
  -d '{"refresh":"eyJ0eXAiOiJ...blabla"}' \
  https://localhost/api/v1/token/refresh

I always get back bad request from my backend where my curl cmd gets trough so I guess I dont understand/see where and how to use http-data with resting. Can smb help?

**Comment by mirkoperillo** [comment]
Hi @venomone 

The translation of this curl call in Resting should be:
POST url
Tab Headers -> Content-Type application/json
Tab Body -> type Raw, copy your json in the textarea provided (without initial and final `'`)

The `--insecure` option tells curl not trying to validate the server certificate, Resting currently shouldn't do any validation on a certificate provided by the server in a  TLS connection.

Let me know if this helps you or try to give me more details.
