### ISSUE TITLE
Additional timestamp queryparam causing issues with some APIs

### ISSUE THREAD

**Issue by nikhilraojl** [mirkoperillo/resting#200]
## Expected Behavior
When using resting to call an API like https://api.openf1.org/v1/drivers?driver_number=1&session_key=9158, I expect to get a response with some json data, refer https://openf1.org/

## Actual Behavior
Instead I just get an empty json array

## Steps to Reproduce the Problem
  1. make a GET request to https://api.openf1.org/v1/drivers?driver_number=1&session_key=9158
  2. observe that the response is just an empty array
 
## Possible fix
It seems that jquery adds an additional `_` timestamp queryparam when using `cache: false` option to construct a ajax request in `src/js/app/request.js/`. jquery doc https://api.jquery.com/jQuery.ajax/#jQuery-ajax-settings
Removing `cache: false` fixes this problem i.e I am getting proper response object instead of an empty array. 

If this is fine as a fix I can make a PR

**Comment by mirkoperillo** [comment]
Hi @nikhilraojl.

I'm absolutely agree with you. Sometimes I have the same problem with some APIs.

It would be great to have a PR about it

**Comment by mirkoperillo** [comment]
@nikhilraojl  I've just released the new version of Resting v1.9.1 with this fix.
Available both for Firefox and Chrome.
