### ISSUE TITLE
Export Bookmark Folder or single bookmark

### ISSUE THREAD

**Issue by vwidmer** [mirkoperillo/resting#206]
## Expected Behavior

Export just a selected Bookmark Folder or Task

## Actual Behavior

Exports everything

## Steps to Reproduce the Problem

  1. Click export button
 

## Specifications

Not sure if its possible but would be nice if can just export specific Folders or Task instead of all. 

I have lots of saved bookmarks and sometimes need to share one to a dev or friend. 

  - Addon Version:
  - Firefox Version:
  - OS:

**Comment by mirkoperillo** [comment]
Hi @vwidmer,

export a folder is for sure a useful feature.

I put it in my backlog of activities for the next release.

The idea could be replacing the current delete button with a more complete context menu of actions available for folders (something like the menu existent for the bookmarks)

![Selezione_080](https://github.com/user-attachments/assets/7aae2e6b-22e9-41d5-a5cb-23332be7f96c)

Just a question, what do you intend for "export a Task" ? Do you intend the possibility to export a single bookmark ?

**Comment by vwidmer** [comment]
@mirkoperillo, 

Yes sometimes I create a project in a folder but don't want to export all or even the complete folder. Sometime just need a single task to show etc..

Thanks again for this great add-on.

**Comment by mirkoperillo** [comment]
@vwidmer the last release of Resting (v1.10.0) includes this feature

**Comment by vwidmer** [comment]
@mirkoperillo: very nice. Thanks for the update.
