### ISSUE TITLE
Security issue on calling an URL

### ISSUE THREAD

**Issue by alexmario74** [mirkoperillo/resting#5]
I load the _index.html_ file in the browser (firefox v57.0.2 (64 bit) on Windows) and then try to call the url: _http://localhost:8080/hello _ (I have a fake server that respond on that address.

I have no feedback from the app, if I check the console I found an error that complain about the absence of the CORS header **Access-Control-Allow-Origin**.

**UPDATE:**

If I remove the _http://_ part of the URL in the field and use the address just like _localhost:8080/hello_ have no errors, but still show any response from the server.

Looking the firebug network panel with the request I could see the response text.

**Comment by alexmario74** [comment]
No bug, just an issue with the _fake server_ that should use the header _Access-Control-Allow-Origin_ to avoid the error.

But still the app is not providing any usefull feedback on such errors.

**Comment by mirkoperillo** [comment]
When the code is used outside the WebExtension context it falls into the CORS problems.
Use it inside WebExtension context permits to avoid this issues thanks to some particular permissions.

But you have right, actually there isn't a management of call errors at view side
