### ISSUE TITLE
Har support

### ISSUE THREAD

**Issue by albertotn** [mirkoperillo/resting#51]
Both firefox and chrome has in developer tools option to export any request in har format.
You should evaluate to let users import this format into resting, for further elaborations

**Comment by mirkoperillo** [comment]
Interesting stuff for the future import feature

**Comment by mirkoperillo** [comment]
Specialization of #14

**Comment by mirkoperillo** [comment]
close in 94b68ffacb4bb7186ffc578680b18a09a505d177
