### ISSUE TITLE
Support for file upload

### ISSUE THREAD

**Issue by albertotn** [mirkoperillo/resting#53]
How to upload file using resting ?

Take as example this call using CURL:

`curl -X POST "http://localhost:8080/test/rest/test/674/import/test" -H  "accept: application/json" -H  "Content-Type: multipart/form-data" -F "upfile=@test.test;type="`

It's possible to select a file and the upload to rest service?

**Comment by mirkoperillo** [comment]
Actually this feature is totally missing.

**Comment by albertotn** [comment]
It's possible to include this feature on next major release ?

**Comment by mirkoperillo** [comment]
Hi @albertotn,

this feature will be present in the next major version.
You can see the list of features for the next major [here](https://github.com/mirkoperillo/resting#roadmap)

**Comment by mirkoperillo** [comment]
@albertotn  finally this feature is available in version 1.4.0

**Comment by albertotn** [comment]
how to enable this in the interface ? I'm not able to see any dedicated button to specify my local file

**Comment by mirkoperillo** [comment]
You should have Resting v1.4.0 almost
Then in the Body tab of the request you have to select `form-data` type

A new dropdown will appear near `name` field with values `Text` or `File`

![Selezione_032](https://user-images.githubusercontent.com/4171821/188559140-c67707db-0dad-40d2-8bd2-f2beeb63f0a8.png)

**Comment by albertotn** [comment]
so it's fine, thanks!
