### ISSUE TITLE
eslint of the project

### ISSUE THREAD

**Issue by alexmario74** [mirkoperillo/resting#59]
This is an issue for those that want to contribute.

Most of the code of the project breacks the lint rules defined by the _.eslintrc.yml_, for example the newline that is in _CRLF_ instead of _LR_.

For people that use ide or editors like _VS Code_ this means an error in each line, only for that rule.

And many other code styles are broken, the errors are a lot.

I think this is something to address for the healt of the project.

I'll can fix most of the issue easily, but (as you can understand) it will imply a huge change of the codebase and issues in diffs.

I think it can be scheduled one file at time (1 file 1 PR) to avoid impacts on the releases.

Once a file is fixed is just a matter of following the linting rules for new features or bug fixing.

**Comment by mirkoperillo** [comment]
@alexmario74  thank you for reporting this, you are right. I introduced eslint to learn about linting, then I didn't use it regularly.
I'll focus on it as soon as possible

**Comment by mirkoperillo** [comment]
Hi @alexmario74, I decided to remove eslint from the project because I've never use it in the last two years.
I close this issue
