### ISSUE TITLE
Use Esc to close a dialog

### ISSUE THREAD

**Issue by mirkoperillo** [mirkoperillo/resting#67]

**Comment by vanholler** [comment]
I'd like to add that. =)

**Comment by mirkoperillo** [comment]
wow @vanholler thank you.
Feel free to ask for every doubt.

**Comment by vanholler** [comment]
@mirkoperillo  can I ask you something? If you make me an official contributor, I could help you all the time. And I can do more complex tasks because I have 3 years of experience in javaScript and I work as a web developer, I can help you more, than move button =)

**Comment by mirkoperillo** [comment]
wow @vanholler I'm very happy that you want to contribute in a continuative way to Resting.
Issues flag with Hacktoberfest are very easy and isolated UI tasks. 
If you are interested to be a long-term contributor feel free to choose every issue you can found in the list to gain knowledge about Resting internals
If I can suggest an interesting and structured issue take a look here #42, but, another time, feel free to choose everything you retain interesting.
