### ISSUE TITLE
Every copy action (CTRL+C) triggers response copy to clipboard

### ISSUE THREAD

**Issue by mirkoperillo** [mirkoperillo/resting#71]
When I try to copy everything present on page ( for example the URL of the request) using CTRL+C, the action triggers the response copy action.

So the result is that the clipboard contains the response body instead of the URL of the request

**Comment by alexmario74** [comment]
It is definitely the clipboard component.

The guard condition just check if the target element is present, and that is all the time.

The fix should be to improve the guard condition.

Will open a PR.

**Comment by mirkoperillo** [comment]
@alexmario74  thank you for contribute.
Your contribution will be surely shipped in next Resting release ( v0.10.0)

**Comment by alexmario74** [comment]
This too was a bug introduced by me... 😳
