### ISSUE TITLE
headers is undefined the first time

### ISSUE THREAD

**Issue by alexmario74** [mirkoperillo/resting#73]
I notices that on the first request there is an error on the clipboard about the headers that is undefined.

As it is just need a default value I'm going to push a new PR for this fix too.

**Comment by mirkoperillo** [comment]
@alexmario74 thank you for reporting and fixing it.
Your PR will be merged and shipped in next release v0.10.0

Thank you for contribute in Resting

**Comment by alexmario74** [comment]
No problem, actually it was a bug introduced by me... 😄

**Comment by mirkoperillo** [comment]
fixed by PR #74
