### ISSUE TITLE
Reset button leaves the last query string element

### ISSUE THREAD

**Issue by alexmario74** [mirkoperillo/resting#76]
## Expected Behavior

When the "Reset" button is pressed all the information about the current request should be clean up.

## Actual Behavior

In the query string the values of the first element are still there.

## Steps to Reproduce the Problem

  1. setup a request to an api with more than one query string element

![image](https://user-images.githubusercontent.com/1519470/54864794-5c288480-4d5c-11e9-893f-7e085759d65f.png)

  1. perform the request
  1. press the "Reset" button.

![image](https://user-images.githubusercontent.com/1519470/54864800-6ba7cd80-4d5c-11e9-902c-6b9848fca1eb.png)

Resting v0.10

  - Firefox Version: 65.0.2
  - OS: Windows 10

**Comment by alexmario74** [comment]
I notices now that if you add an empty field at the bottom, the reset works.

Here is what I mean:

![image](https://user-images.githubusercontent.com/1519470/54864860-65feb780-4d5d-11e9-88e2-dab33f559ef5.png)

And after the reset:

![image](https://user-images.githubusercontent.com/1519470/54864865-6eef8900-4d5d-11e9-9d60-44b06996531a.png)

**Comment by mirkoperillo** [comment]
Hi @alexmario74,

to add a field to querystring ( and in the other similar widgets) you should explicitly click + button for every field row.
Watching the first screenshot, the end field is not added but you have only inserted the values in the text fields.
( if field is correctly added it should appear the trash icon button near the field..as you see in the third screenshot).

The user experience must be improved definitely

**Comment by alexmario74** [comment]
You're right, about the value, but still the reset had a weird behaviour.

I was expected that all the field are cleaned up.

**Comment by mirkoperillo** [comment]
You are absolutely right, I close this issue and I open a specialized issue about
