### ISSUE TITLE
Move add folder button

### ISSUE THREAD

**Issue by mirkoperillo** [mirkoperillo/resting#91]
Move the add folder button from the header of bookmarks panel.
Its new position should be as first button in the button group inside the bookmarks panel body (near the import and export buttons)

**Comment by andrewdazs** [comment]
I would like to solve this issue :)

**Comment by mirkoperillo** [comment]
Hi
you are welcome, feel free to ask if you need

Il giorno gio 26 set 2019 alle ore 02:21 Andrew <notifications@github.com>
ha scritto:

**Comment by vanholler** [comment]
Hey. I'd like to try to help you. Can I get a little more information about the task?

**Comment by vanholler** [comment]
Hey. I'd like to try to help you. Can I get a little more information about the task?

**Comment by mirkoperillo** [comment]
Hi @vanholler thank you for your interest.
I think that Andrew is already working on this.

Stay tuned because in the next days I'll open other issues on Resting

**Comment by vanholler** [comment]
> Hi @vanholler thank you for your interest.
> I think that Andrew is already working on this.
> 
> Stay tuned because in the next days I'll open other issues on Resting

Oh sorry, I just don't understand the letter before me, but I would love to try their hand at new tasks.

**Comment by andrewdazs** [comment]
Hi @vanholler, feel free to resolve this issue, I don't know if I'll have time to resolve it :/

**Comment by vanholler** [comment]
if @mirkoperillo  don't mind, I'll try it this week.

**Comment by mirkoperillo** [comment]
@vanholler for me it's ok
Thank you to contribute to Resting.
If you have any problem feel free to ask

**Comment by vanholler** [comment]
Hey. I did. is it supposed to look like this ?
![screenshot](https://user-images.githubusercontent.com/32782411/66523248-195fab80-eaf8-11e9-94fa-fcc0c28840e9.png)

**Comment by mirkoperillo** [comment]
@vanholler this is exactly what I have imaged

**Comment by vanholler** [comment]
@mirkoperillo I was glad to do it. If I can try to do anything else from?

**Comment by mirkoperillo** [comment]
Fix via 5d1448b005b183dd496622e6718339d79581ccd1
