### ISSUE TITLE
jqXHR.responseText is undefined

### ISSUE THREAD

**Issue by albertotn** [mirkoperillo/resting#94]
## Expected Behavior

When user call a GET for https://api.seeker.company/v1/ping, should work

## Actual Behavior

Right now is blocked in firefox, with error in console "TypeError: jqXHR.responseText is undefined"

## Steps to Reproduce the Problem

  1. create a new request
  1. set GET method
  1. url as https://api.seeker.company/v1/ping
  1. send

## Specifications

  - Addon Version: 0.13.0
  - Firefox Version: 69.0.2
  - OS: Windows 10

**Comment by alexmario74** [comment]
I think your console error is not the actual error, instead I think the request to the api.seeker.company failed for some reason.

But unfortunately on the error callback there is the use of the _jqXHR.responseText.length_ unchecked.

As the request failed the _responseText_ might not be present.

I repeat your test and it is working fine for me now.
Have the same browser and extension version as you.

But if I change the url with a non existing one, I got your same error on console.

I can fix this too.
